[pytest]

# 注册自定义标记
markers =
    smoke: 冒烟用例，只跑核心功能
    regression: 回归测试，跑完整流程

# 默认参数 — 就不用每次都敲 pytest -v 了
addopts =-vs

# 测试发现规则
testpaths = .
python_files = test_*.py



; [pytest] — 固定格式，告诉 pytest 这是它的配置段
; markers = — 宣告你有哪些自定义标签，冒号后面是给人看的描述
; addopts = -v — 相当于每次执行 pytest 自动帮你加 -v
; testpaths = . — 从哪个目录开始找测试
; python_files = test_*.py — 哪些文件名算测试文件（默认就是这个）


